# Semantic Release Configuration
# https://semantic-release.gitbook.io/semantic-release/usage/configuration

branches:
  - name: master

plugins:
  # Analyze commit messages to determine next version
  - "@semantic-release/commit-analyzer"

  # Generate release notes
  - "@semantic-release/release-notes-generator"

  # Generate changelog
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md

  # Replace version strings and build packages
  - - "@semantic-release/exec"
    - shell: true
      prepareCmd: |
        sed -i '0,/^version = "[0-9]\+\.[0-9]\+\.[0-9]\+"$/s//version = "${nextRelease.version}"/' Cargo.toml
        sed -i 's/^Version: .*/Version: ${nextRelease.version}/' pkg/rpm/cosmic-files.spec
        task docker:run TARGET=dist:all ARCH=x86_64 TARGET_ARCH=x86_64-unknown-linux-gnu
        task docker:run TARGET=dist:all ARCH=aarch64 TARGET_ARCH=aarch64-unknown-linux-gnu

  # Commit the following changes to git after other plugins have run
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - Cargo.toml
        - Cargo.lock
        - pkg/rpm/cosmic-files.spec

  # Create a GitHub release with RPM assets
  - - "@semantic-release/github"
    - assets:
        - path: "dist/*x86_64*.rpm"
          label: "RPM (x86_64)"
        - path: "dist/*aarch64*.rpm"
          label: "RPM (aarch64)"
      successComment: false
      failComment: false
